print("My AGI Journey begins.")
name = input("Enter your name: ")
age = int(input("Enter your age: "))
height = float(input("Enter your height in meters: "))
is_student = input("Are you a student? (yes/no): ")
print("Your Details:")
print("Name:", name)
print("Age:", age)
print("Height:", height)
print("Student:", is_student == "yes")